[project]
name = "py-play-money"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Jean-Gabriel Young", email = "jean.gabriel.young@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "pydantic>=2.10.6",
    "requests>=2.32.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
